<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>8bc29c9d-941b-4a84-98cf-373a781ab902</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.13.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GerenciadorDeLivro.Application\GerenciadorDeLivro.Application.csproj" />
      <ProjectReference Include="..\GerenciadorDeLivro.Core\GerenciadorDeLivro.Core.csproj" />
      <ProjectReference Include="..\GerenciadorDeLivro.Infrastructure\GerenciadorDeLivro.Infrastructure.csproj" />
    </ItemGroup>

</Project>
